version: '3'
services:
  api:
    build: .
    ports:
      - "9000:900"
    volumes:
      - .:/var/www/app

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
